# March Machine Learning Mania 2026

![pic](https://i.pinimg.com/736x/80/aa/63/80aa63d1c9371ee220ab8140492f94fa.jpg)


|No| Name  | Notebook |
| --- | ------ | ------- |
| 00 | Dataset |  https://www.kaggle.com/competitions/march-machine-learning-mania-2026/data |
| 01 | Understand Data Structure  | https://www.kaggle.com/code/rudraprasadbhuyan/ncaa-p1-dataset-overview-structure-understanding/ |
| | |  |

In [ ]:
import os
import numpy as np
import pandas as pd

After this notebook, we understand:

- Dataset structure
- Relationship between files
- How seasons are organized
- How tournaments are structured
- How submission format works
- Where modeling data will come from

# Basic

> Few terms that is need to understand if you are beginner just like me.
>
> *AI Generated

**What is NCAA?**

**NCAA** = *National Collegiate Athletic Association*

It is the organization that runs sports competitions for **U.S. colleges and universities**.

Think of it like:

* FIFA → controls World Cup (soccer)
* NBA → professional basketball league
* **NCAA → college basketball tournaments**

Every year they organize a big tournament called **March Madness**.



**What is a Team?**

A **team** is a college basketball team.

Example:

* Duke University basketball team
* Kansas University basketball team

In the dataset:

* Each team has a **TeamID** (a number)
* Example: TeamID = 1104
* That number represents one specific college team

Important:
The same team plays every year, but their players change.


**What is a Seed?**

A **seed** = ranking number given before the tournament starts.

It shows how strong a team is expected to be.

Think of it like:

* Seed 1 → very strong team
* Seed 16 → weak team

Each region has seeds:
1, 2, 3, … up to 16

Example:
W01 = Region W, Seed 1 (very strong)
X16 = Region X, Seed 16 (underdog)

Why seeds matter:
Higher seed teams usually win more often.


**What is DayNum?**

DayNum = Day Number of the season.

Instead of real dates (Jan 10, Feb 2, etc.), they count days from the start of the season.

Example:

* DayNum 0 → first day of season
* DayNum 132 → Selection Sunday (seeds announced)
* DayNum 154 → Championship game

Why they use DayNum:
It makes it easier to compare seasons without worrying about calendar dates.



**What is the Tournament?**

After the regular season:

1. Best teams are selected
2. They are given seeds
3. They play knockout matches
4. Loser is eliminated
5. Winner continues
6. Final winner = National Champion

It’s like:
World Cup knockout stage.



**What is Regular Season?**

Before the tournament, teams play many games.

These games:

* Help determine how strong teams are
* Help decide tournament selection

This data is used to:

* Calculate team strength
* Train prediction models



**What is in the Dataset?**

The dataset gives:

* Which team played which team
* Who won
* Score
* Location (home/away/neutral)
* Seed
* Season year

Your job in Kaggle:
Predict the probability that Team A beats Team B in the tournament.



**Very Simple Summary**

- NCAA → Organization that runs college basketball
- Team → A college basketball team
- Season → One year of games
- DayNum → Day number inside that season
- Seed → Pre-tournament ranking (1 = strongest)
- Tournament → Knockout competition to decide champion

In [ ]:
folder_path = r"C:\Users\Rudra\Desktop\kaggle\NCAA\data" # Replace 'data' with your folder's path if it's different

try:
    all_entries = os.listdir(folder_path)
    
    files_list = [entry for entry in all_entries if os.path.isfile(os.path.join(folder_path, entry))]
    
    print("Files in the 'data' folder:")
    for file_name in files_list:
        print(file_name)

except FileNotFoundError:
    print(f"Error: The directory '{folder_path}' does not exist.")

Files in the 'data' folder:
Cities.csv
Conferences.csv
MConferenceTourneyGames.csv
MGameCities.csv
MMasseyOrdinals.csv
MNCAATourneyCompactResults.csv
MNCAATourneyDetailedResults.csv
MNCAATourneySeedRoundSlots.csv
MNCAATourneySeeds.csv
MNCAATourneySlots.csv
MRegularSeasonCompactResults.csv
MRegularSeasonDetailedResults.csv
MSeasons.csv
MSecondaryTourneyCompactResults.csv
MSecondaryTourneyTeams.csv
MTeamCoaches.csv
MTeamConferences.csv
MTeams.csv
MTeamSpellings.csv
SampleSubmissionStage1.csv
SampleSubmissionStage2.csv
WConferenceTourneyGames.csv
WGameCities.csv
WNCAATourneyCompactResults.csv
WNCAATourneyDetailedResults.csv
WNCAATourneySeeds.csv
WNCAATourneySlots.csv
WRegularSeasonCompactResults.csv
WRegularSeasonDetailedResults.csv
WSeasons.csv
WSecondaryTourneyCompactResults.csv
WSecondaryTourneyTeams.csv
WTeamConferences.csv
WTeams.csv
WTeamSpellings.csv

In [ ]:
def sample_df(file_name):
    """
    Reads a CSV file from a set data_folder_path and returns 5 random samples.
    """
    data_folder_path = r"/kaggle/input/march-machine-learning-mania-2026"
    file_path = os.path.join(data_folder_path, file_name)
    df = pd.read_csv(file_path)
    display(df.sample(5))
    del df

# Data Section 1 - The Basics

- Here the file which is start with `M` means -> Men
- If start with `F` -> Female
- We have more data on male

## 1. Team

In [ ]:
sample_df('MTeams.csv')

   TeamID     TeamName  FirstD1Season  LastD1Season
0    1101  Abilene Chr           2014          2026
1    1102    Air Force           1985          2026
2    1103        Akron           1985          2026
3    1104      Alabama           1985          2026
4    1105  Alabama A&M           2000          2026

## 2. Seasons

In [ ]:
sample_df('MSeasons.csv')

    Season     DayZero RegionW    RegionX  RegionY RegionZ
9     1994  11/01/1993    East  Southeast  Midwest    West
31    2016  11/02/2015    East    Midwest    South    West
22    2007  10/30/2006    East      South  Midwest    West
13    1998  10/27/1997    East       West  Midwest   South
35    2020  11/04/2019     NA1        NA2      NA3     NA4

## 3. Tournament Seeds

In [30]:
sample_df('MNCAATourneySeeds.csv')

      Season  Seed  TeamID
1568    2009   X09    1139
710     1996   W07    1307
2107    2017   X08    1321
2455    2023  X16b    1394
626     1994   Z03    1257

Season

Seed (Region + Seed number, e.g., W01, X16a)

TeamID

## 4. Regular Season Results (Compact)

In [32]:
sample_df('MRegularSeasonCompactResults.csv')

        Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
28170     1992      33     1344      77     1348      74    H      0
173360    2022      77     1231      78     1304      71    A      0
33823     1993      85     1378      77     1416      72    A      0
73999     2002     130     1242     102     1160      73    N      0
11814     1988      33     1389      71     1198      61    N      0

Season

DayNum

WTeamID / LTeamID

WScore / LScore

WLoc (H/A/N)

NumOT

- This helps to build team strength metrics

## 5. NCAA Tournament Results (Compact)

In [33]:
sample_df('MNCAATourneyCompactResults.csv')

      Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
592     1994     137     1277      84     1371      73    N      0
1259    2004     146     1181      66     1462      63    N      0
2378    2022     145     1437      50     1222      44    N      0
948     2000     136     1235      88     1148      78    N      0
1286    2005     137     1235      64     1278      53    N      0

- Same format as regular season results, but only tournament games.

## 6. Sample Submission

In [34]:
sample_df('SampleSubmissionStage1.csv')

                    ID  Pred
443183  2025_1329_1444   0.5
485164  2025_3208_3427   0.5
189216  2023_1389_1468   0.5
379382  2024_3343_3375   0.5
299980  2024_1255_1342   0.5

- ID = Season_LowerTeamID_HigherTeamID
- Pred = probability lower TeamID wins

# Section 2 — Detailed Box Score Data

In [35]:
sample_df('MRegularSeasonDetailedResults.csv')

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
121704,2026,71,1385,92,1266,68,H,0,33,65,...,15,17,27,5,17,10,19,7,4,17
85746,2019,92,1405,63,1103,52,H,0,24,60,...,21,13,16,10,32,3,8,2,1,17
40408,2011,33,1175,64,1271,53,H,0,24,50,...,15,8,10,7,21,11,15,3,1,14
80481,2018,96,1368,89,1146,84,H,0,31,58,...,19,7,10,5,20,14,17,3,4,25
89727,2020,61,1186,71,1340,69,H,0,30,61,...,18,8,14,12,26,15,7,7,3,16

In [36]:
sample_df('MNCAATourneyDetailedResults.csv')

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
1306,2023,144,1361,71,1104,64,N,0,26,69,...,27,15,20,18,32,10,14,5,5,22
998,2018,136,1397,73,1460,47,N,0,27,60,...,21,5,9,11,21,9,13,5,2,17
1238,2022,144,1274,70,1235,56,N,0,26,56,...,22,2,4,14,23,16,16,6,4,18
528,2011,136,1396,66,1336,64,N,0,24,49,...,19,4,6,8,18,12,9,4,0,13
690,2013,139,1181,66,1166,50,N,0,19,49,...,19,16,18,7,26,9,10,2,2,26

# Section 3 — Geography Data

In [37]:
sample_df('Cities.csv')

     CityID               City State
236    4237        New Orleans    LA
195    4196        Little Rock    AR
247    4248  North Little Rock    AR
162    4163             Irvine    CA
178    4179           Kingston    RI

In [38]:
sample_df('MGameCities.csv')

       Season  DayNum  WTeamID  LTeamID   CRType  CityID
88941    2026      57     1370     1450  Regular    4313
45446    2018      50     1190     1178  Regular    4098
70348    2023      22     1406     1164  Regular    4348
52028    2019      73     1167     1282  Regular    4021
3508     2010      91     1370     1186  Regular    4313

# Data Section 4 - Public Rankings

In [41]:
sample_df('MMasseyOrdinals.csv')

         Season  RankingDayNum SystemName  TeamID  OrdinalRank
1342966    2011             72        RTB    1205          284
3330652    2018             86        KPK    1440          319
1008723    2009            126        SIM    1447          235
4944077    2023            133        WMV    1127          307
2910898    2017             37        KPK    1326           49

# Section 5 — Supplemental Information

## Conferences

* Conferences.csv
* MTeamConferences.csv
* WTeamConferences.csv

Track team conference affiliation over time.

In [42]:
sample_df('Conferences.csv')

   ConfAbbrev                  Description
19        ecc        East Coast Conference
3         acc    Atlantic Coast Conference
8   big_eight         Big Eight Conference
21        gsc         Gulf Star Conference
49        wac  Western Athletic Conference

In [43]:
sample_df('MTeamConferences.csv')

       Season  TeamID  ConfAbbrev
5698     2003    1425     pac_ten
7986     2010    1353    big_east
12577    2023    1390  pac_twelve
10887    2018    1464     horizon
2223     1992    1348       a_ten

## Conference Tournament Games

* MConferenceTourneyGames.csv
* WConferenceTourneyGames.csv

Identify games that were conference tournaments.

In [44]:
sample_df('MConferenceTourneyGames.csv')

      Season ConfAbbrev  DayNum  WTeamID  LTeamID
1996    2008        sec     130     1208     1246
4792    2018       swac     130     1115     1380
5977    2023    patriot     125     1159     1119
1262    2006  big_south     120     1219     1347
4664    2018        caa     125     1456     1406

## Secondary Tournaments

* NIT, WNIT, etc.
* MSecondaryTourneyCompactResults.csv
* WSecondaryTourneyCompactResults.csv

These games happen after DayNum 132.

In [45]:
sample_df('MSecondaryTourneyCompactResults.csv')

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,SecondaryTourney
225,1992,135,1130,78,1356,69,H,0,NIT
1429,2017,135,1227,71,1392,69,H,0,CBI
269,1993,135,1425,90,1424,74,A,0,NIT
352,1996,135,1104,72,1228,69,A,0,NIT
406,1997,141,1304,78,1305,68,A,0,NIT

## Coaches

* MTeamCoaches.csv

Track coaching changes during season.

In [46]:
sample_df('MTeamCoaches.csv')

       Season  TeamID  FirstDayNum  LastDayNum        CoachName
5324     2002    1314            0         154     matt_doherty
13268    2025    1208            0         154       mike_white
13017    2024    1326            0          99   chris_holtmann
13457    2025    1403            0         154  grant_mccasland
7735     2009    1375            0         154     ronnie_arrow

## Alternative Team Spellings

* MTeamSpellings.csv
* WTeamSpellings.csv

Used for mapping external datasets.

In [47]:
sample_df('MTeamSpellings.csv')

          TeamNameSpelling  TeamID
1070             ut-martin    1404
640            nicholls st    1311
73                 ball-st    1123
297       fort wayne(ipfw)    1236
1090  vcu(va. commonwealth    1433

## Bracket Structure

* MNCAATourneySlots.csv
* MNCAATourneySeedRoundSlots.csv
* WNCAATourneySlots.csv

Defines:

* How seeds are paired
* How bracket progresses
* Round mapping

This is useful for tournament simulation.

In [48]:
sample_df('MNCAATourneySeedRoundSlots.csv')

     Seed  GameRound GameSlot  EarlyDayNum  LateDayNum
687  Z12a          5     R5YZ          152         152
469  Y11a          1     R1Y6          136         137
149  W14b          2     R2W3          138         139
717   Z14          2     R2Z3          138         139
53    W09          6     R6CH          154         154

In [49]:
sample_df('MNCAATourneySlots.csv')

      Season  Slot StrongSeed WeakSeed
1013    2001  R1W6        W06      W11
2550    2025  R1Z8        Z08      Z09
1423    2007  R1Z8        Z08      Z09
1226    2004  R1Z3        Z03      Z14
2174    2018  R4X1       R3X1     R3X2

# Data Flow

Season

→ Teams

→ Regular Season Games

→ Conference Tournaments

→ Selection Sunday (DayNum 132)

→ Seeds Assigned

→ NCAA Tournament

→ Champion

All of this is connected through:
Season + TeamID + DayNum